version: '3'

services:
  postgres_meta:
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_SER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5467:5432
    volumes:
      - my_data:/var/lib/postgresql/data

volumes:
  my_data: