version: '3'

services:
  postgres_meta:
    build: .
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5467:5432
    volumes:
      - ./test.sql:/docker-entrypoint-initdb.d/test.sql

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db


volumes:
  dbdata6: